############################
# Módulos (formato nuevo)
############################
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

############################
# Autodiscover de Docker
############################
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        enabled: false

filebeat.modules:
  - module: nginx
    access:
      enabled: true
      var.paths: ["/var/log/nginx/access.log"]
    error:
      enabled: true
      var.paths: ["/var/log/nginx/error.log"]

############################
# Procesadores
############################
processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_host_metadata:
      when.not.regexp:
        system.os.platform: windows
  - add_cloud_metadata: ~

############################
# Dashboards + Kibana
############################
setup.dashboards:
  enabled: true

setup.kibana:
  host: "${KIBANA_HOSTS}"
  protocol: "https"
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["${CA_CERT}"]

############################
# Salida a Elasticsearch
############################
output.elasticsearch:
  hosts: ["${ELASTIC_HOSTS}"]
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["${CA_CERT}"]

############################
# Logging
############################
logging:
  level: info
  to_files: false
  to_stderr: true
  selectors: ['*']
