############################
# Dashboards + Kibana setup
############################
setup.dashboards:
  enabled: true

setup.kibana:
  host: "${KIBANA_HOSTS}"
  protocol: "https"
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["${CA_CERT}"]

###################
# Packet configuration
###################
packetbeat.interfaces.device: any

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
  - type: icmp
    enabled: true
  - type: dhcpv4
    ports: [67, 68]
  - type: dns
    ports: [53]
  - type: http
    ports: [80, 8080, 8000, 5000, 8002]
  - type: tls
    ports:
      - 443
      - 993
      - 995
      - 5601
      - 9200
  - type: mysql
    ports: [3306, 3307]
  - type: redis
    ports: [6379]
  - type: pgsql
    ports: [5432]
  - type: mongodb
    ports: [27017]

#########################
# Procesadores genéricos
#########################
processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
  - add_docker_metadata: ~

#########################
# Salida a Elasticsearch
#########################
output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ["${CA_CERT}"]

##########
# Logging
##########
logging:
  level: info
  to_files: false
  to_stderr: true
  selectors: ['*']
