############################
# Dashboards + Kibana setup
############################
setup.dashboards:
  enabled: true
  index: "metricbeat-*"

setup.kibana:
  host: "${KIBANA_HOSTS}"
  protocol: "https"
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["${CA_CERT}"]

#####################################
# Carga de módulos al estilo moderno
#####################################
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

#####################################
# Autodiscover (por si lo quieres usar)
#####################################
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

###################
# Módulos activos
###################
metricbeat.modules:
  # Métricas del propio cluster de Elasticsearch
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ${ELASTIC_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    ssl:
      enabled: true
      certificate_authorities: ["${CA_CERT}"]

  # Métricas de Kibana
  - module: kibana
    metricsets:
      - stats
    period: 10s
    hosts: ${KIBANA_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    xpack.enabled: true
    ssl:
      enabled: true
      certificate_authorities: ["${CA_CERT}"]

  # Métricas de Docker
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  # Métricas de Nginx (stub_status)
  - module: nginx
    metricsets:
      - stubstatus
    period: 10s
    hosts: ["http://nginx-app:80/nginx-status"]
    server_status_path: "/nginx-status"
    enabled: true

#########################
# Procesadores genéricos
#########################
processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
  - add_docker_metadata: ~

#########################
# Salida a Elasticsearch
#########################
output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ["${CA_CERT}"]

##########
# Logging
##########
logging:
  level: info
  to_files: false
  to_stderr: true
  selectors: ['*']
